Novetta/adaptnlp

adaptnlp/__init__.py, adaptnlp/__main__.py, adaptnlp/embeddings.py, adaptnlp/file_utils.py, adaptnlp/question_answering.py, adaptnlp/sequence_classification.py, adaptnlp/token_classification.py, adaptnlp/training.py, adaptnlp/transformers/__init__.py, adaptnlp/transformers/finetuning.py, adaptnlp/transformers/question_answering.py, adaptnlp/transformers/utils_squad.py, adaptnlp/transformers/utils_squad_evaluate.py, requirements.txt, rest/app/main.py, setup.cfg, setup.py, tests/test_language_model_fine_tuner.py, tests/test_question_answering.py, tests/test_sequence_classifier.py, tests/test_sequence_classifier_trainer.py, tests/test_token_tagger.py, tests/test_trained_embeddings.py, tutorials/5. Finetuning and Training (Advanced)/sequence_classification_training.ipynb
Format adaptnlp/ with black
Format rest/ with black
Fix initial testing suite to run with no error
Fix sequence classification tutorial bug
Fix QA module `n_best_size`param in documentation
=> Update adaptnlp and fastapi module with black and fix some bugs 

README.md, adaptnlp/transformers/finetuning.py, docs/index.md
Add dockerhub link to features.
Update and fix spacing issues for readme in docs.
Correct block size for `TextDataset` in finetuning module and raise better errors for token masking function.
=> Update README and finetuning TextDataset

README.md, docs/index.md
=> Update deprecated predict method for qa module

README.md, docs/index.md
Add a visual of Rest API with Swagger UI on the readme.
Better venv example and more specifics.
Link to official AdaptNLP docker images.
=> Simple Readme Updates

adaptnlp/transformers/finetuning.py, docs/tutorial/fine-tuning-language-model.md, tutorials/5. Finetuning and Training (Advanced)/fine_tuning.ipynb
Closes #12 
Addressed some updates to finetuning module and documentation regarding bad defaults for apex
=> Apex bug fix in finetuner param and documentation update

.circleci/config.yml, README.md, docs/index.md, docs/requirements.txt
Deploy to github pages with mkdocs
Address readme doc links
Add circleci workflow job to deploy doc on master branch
Fixes #14
=> Transfer Documentation to Github Pages and add doc deploy workflow in CircleCI

.circleci/config.yml, README.md, docs/index.md
=> Attempt to fix ci skip on doc deploy

rest/requirements.txt
Update to FastAPI 0.52.0.
Add additional features that may come up.
=> Add 49 tag for #22 to start updating to latest fastapi version

tests/test_token_tagger.py
=> Revert "add base EasyTokenTagger tests #19"

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/questions.md
Add bug, feature, and question issue templates
=> Update issue templates

.circleci/config.yml
=> Add nightly build in circleci workflow to close #33

adaptnlp/__init__.py, adaptnlp/sequence_classification.py, adaptnlp/summarization.py, docs/class-api/question-answering-module.md, docs/class-api/sequence-classifier-module.md, docs/class-api/summarizer-module.md, mkdocs.yml, rest/README.md, rest/app/main.py, tests/test_summarizer.py
Use Bart and T5 Models to add `EasySummarizer` and class API documentation.  With regards to #43
=> Adding Easy Summarizers Module

README.md, docs/index.md
Fix index.md colab display issues as well
=> Add quickstart examples for summarizer and translator

adaptnlp/__init__.py, adaptnlp/summarization.py, adaptnlp/text_generation.py, adaptnlp/token_classification.py, adaptnlp/translation.py, requirements.txt
Updating pytorch, transformers, flair.  Adding nlp and pandas dependencies.
Added text generation modules and transformers token tagging capabilities.
Updated Translation modules to include pre-trained MarianMT language models that include 1000+ translation models.
=> Update Sweep including Text Generation, Transformers NER/POS/TokenTagging, and Translation Models

docs/tutorial/text-generation.md, mkdocs.yml
Added a page for text generation under tutorials with a summary of what it was and a simple example.
=> Added initial Text Generation Documentation

tests/test_sequence_classifier.py
Quick bug fix in reference to [1841](https://github.com/flairNLP/flair/issues/1841)
=> Use transformers sequence classification for test

docs/rest.md, rest/README.md, rest/question-answering/Dockerfile, rest/question-answering/app/data_models.py, rest/sequence-classification/Dockerfile, rest/sequence-classification/app/main.py, rest/summarization/Dockerfile, rest/summarization/app/data_models.py, rest/summarization/app/main.py, rest/summarization/entrypoint.sh, rest/summarization/requirements.txt, rest/text-generation/Dockerfile, rest/text-generation/app/data_models.py, rest/text-generation/app/main.py, rest/text-generation/entrypoint.sh, rest/text-generation/requirements.txt, rest/token-tagging/Dockerfile, rest/token-tagging/app/data_models.py, rest/token-tagging/app/main.py, rest/translation/Dockerfile, rest/translation/app/data_models.py, rest/translation/app/main.py, rest/translation/entrypoint.sh, rest/translation/requirements.txt
Docker hub images available for:
- Translation: https://hub.docker.com/r/achangnovetta/translation
- Summarization: https://hub.docker.com/r/achangnovetta/summarization
- Text Generation: https://hub.docker.com/r/achangnovetta/text-generation
Cleaned and formatted rest directory.
=> Add new services for translation, summarization, and text generation

rest/question-answering/app/data_models.py, rest/question-answering/app/main.py
Update question answering app to take in multiple queries for batch inference
=> QA Rest Update: Batch Inference

adaptnlp/sequence_classification.py
Issue #99 
Updated predict function for FlairSequenceClassifier, ensuring it doesn't return None
=> updated predict for FlairSequenceClassifier

adaptnlp/callback.py, adaptnlp/embeddings.py, adaptnlp/model.py, adaptnlp/question_answering.py, adaptnlp/sequence_classification.py, adaptnlp/summarization.py, adaptnlp/text_generation.py, adaptnlp/token_classification.py, adaptnlp/translation.py, requirements.txt
In this PR, I've integrated in [fastai_minima](https://pypi.org/project/fastai-minima/) which is a minimal version of the fastai repo, completely frozen on dependencies. 
As a result of this I've integrated the `fastcore`, `fastprogress`, and `fastai` packages whenever possible, including refactoring most code to be utilized with basic `Callbacks`, to allow for modularization. I adjusted the base `model` class to include a private fastai `Learner` to which all things must be sent through, so the user can't really break much.
@aychang95 let me know if there are any questions, this is a very bulky PR
Closes https://github.com/Novetta/adaptnlp/issues/108
=> Full integrate fastcore and fastai, refactor with Callbacks where possible

.github/workflows/main.yml
Adds in automated testing to the builds on each commit, fulfilling both https://github.com/Novetta/adaptnlp/issues/112 and one of the stretch goals in https://github.com/Novetta/adaptnlp/issues/112
Still needed:
- Windows
- Small-scale fine-tune training on CPU efficiently
=> Add automated testing with Mac and Ubuntu + py 3.6-8

adaptnlp/training/core.py, nbs/12_training.core.ipynb, nbs/training_api_tutorials/token_classification/token_classification_from_csv.ipynb, nbs/training_api_tutorials/token_classification/token_classification_from_df.ipynb
Fixed issue #149 in training.core and also added in support to the AdaptiveDataLoader's show_batch to work with token classification (realized that I forgot to do that)
Also completed the token classification tutorials
=> Fixed training.core and Added finished token classification tutorials
